CREATE TABLE tb_user_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE tb_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    user_type_id BIGINT NOT NULL,
    CONSTRAINT fk_user_type FOREIGN KEY (user_type_id) REFERENCES tb_user_types(id)
);

CREATE TABLE tb_restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    cuisine_type VARCHAR(150) NOT NULL,
    operating_hours VARCHAR(150) NOT NULL,
    owner_id BIGINT NOT NULL,
    CONSTRAINT fk_restaurant_owner FOREIGN KEY (owner_id) REFERENCES tb_users(id)
);

CREATE TABLE tb_menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    available_only_in_restaurant BOOLEAN NOT NULL DEFAULT FALSE,
    image_path VARCHAR(512),
    restaurant_id BIGINT NOT NULL,
    CONSTRAINT fk_menu_item_restaurant FOREIGN KEY (restaurant_id) REFERENCES tb_restaurants(id)
);

INSERT INTO tb_user_types (name) VALUES ('DONO_RESTAURANTE');
INSERT INTO tb_user_types (name) VALUES ('CLIENTE');

INSERT INTO tb_users (name, email, password, user_type_id)
VALUES ('Eber Dev', 'eber.l@gmail.com', '$2a$10$coisas_criptografadas', 1);

